name: 'Ben Rodríguez'

description: >
  Set the commit status for workflows triggered by bvr.

inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'

outputs:
  time: # id of output
    description: 'The time we greeted you'

runs:
  using: 'node12'
  main: 'build/bundled/index.js'
