name: 'Ben Rodríguez'

author: Elad Chen

description: >
  Update / Create commit status of a given SHA.

  See https://docs.github.com/en/rest/reference/repos#create-a-commit-status
  
  *Note*:
  This is action is crafted specifically workflows for triggered by Ben Rodriguez (Bot).
  But can be 100 configured using the action inputs.

branding:
  icon: shield
  color: green

inputs:
  token:
    description: 'A Github API authentication token'
    required: false
    default: '${{ github.token }}'

  update-commit-status:
    description: 'enable / disable commit status updates'
    required: false
    default: 'true'

  accept:
    description: 'Create Commit Status "accept" parameter (header)'
    required: false
    default: 'application/vnd.github.v3+json'

  owner:
    description: 'Create Commit Status "owner" parameter (path)'
    required: false

  repo:
    description: 'Create Commit Status "repo" parameter (path)'
    required: false

  sha:
    description: 'Create Commit Status "sha" parameter (path)'
    required: false

  target_url:
    description: 'Create Commit Status "target_url" parameter (body)'
    required: false

  description:
    description: 'Create Commit Status "description" parameter (body)'
    required: false

  context:
    description: 'Create Commit Status "context" parameter (body)'
    required: false

outputs:
  repositoryOwner:
    description: >
      The repository owner is the organization name / github user that owns the
      repository used by this run.

      Note: This output will only be set when the workflow has
      inputs matching those set when Ben Rodriguez (Bot) triggers the run.

  repositoryName:
    description: >
      The repository name used by this run.

      Note: This output will only be set when the workflow has
      inputs matching those set when Ben Rodriguez (Bot) triggers the run.

  commitSHA:
    description: >
      The commit SHA used by this run.

      Note: This output will only be set when the workflow has
      inputs matching those set when Ben Rodriguez (Bot) triggers the run.

runs:
  using: 'node12'
  main: 'build/bundled/index.js'
  post: 'build/bundled/index.js'
